# Generated by Django 5.1.1 on 2024-09-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer360', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='social',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='channel',
            field=models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('sms', 'SMS'), ('letter', 'Letter'), ('social', 'Social')], max_length=15),
        ),
    ]
